# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-12 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('candidate_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(db_index=True, max_length=255)),
                ('email_id', models.EmailField(db_index=True, max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=16)),
                ('qualification', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hiring',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('hiring_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('state_obj_dump', models.TextField(blank=True, null=True)),
                ('machine_obj_dump', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Candidate')),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('job_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('job_role', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('experience_req', models.IntegerField(default=0)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hiring',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Job'),
        ),
        migrations.AddField(
            model_name='hiring',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkflowInfo'),
        ),
    ]
